apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "chart-ruan.labels" . | nindent 4 }}
  {{- if .Values.secret.name }}
  name: {{ .Values.secret.name }}
  {{- else }}
  name: {{ include "chart-ruan.fullname" . }}
  {{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
